name: Python CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install unittest-xml-reporting

    - name: Run tests with unittest
      run: |
        mkdir -p test-reports
        python -m unittest discover -s test -p "*_test.py" > test-reports/report.xml

    - name: List test-reports directory
      run: ls -l test-reports

    - name: Upload test reports
      uses: actions/upload-artifact@v4  # Atualizado para v4
      with:
        name: test-reports
        path: test-reports/report.xml

  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build executable
      run: |
        pip install pyinstaller
        pyinstaller --onefile main.py

    - name: Upload executable
      uses: actions/upload-artifact@v4  # Atualizado para v4
      with:
        name: my_python_executable
        path: dist/main
